### ISSUE TITLE
[bootloader] blocco del sistema in caso di boot incompatibile

### ISSUE THREAD

**Issue by fgalfa** [alfa-sw/sw-programmazione-schede#18]
# Setup
1 scheda MAB + 1 scheda SCCB con indirizzo 1
boot "MAB": "SchedaMAB/BootLoader/bootloaderMABrd_1.0.2.hex"
boot "SLAVE_1": "SchedaSCCB/Bootloader/BootLoaderSCCB_1.5.1.hex" (N.B. boot incompatibile)

# Esecuzione e risultati
si esegue il test N.6 (./tests/compatibility_tests/DESK/run_test.sh 6 app) con app non presenti: OK
dopo riaccensione, in fase di flash app slave, il sistema non risponde più ai comandi ed è necessario riaccendere.

# Log
```
[2021-11-09 11:43:35,940]INFO _observe_events() userlevel.py:506 Event label: EventLabel.STATE_CHANGED, Attachment: State.BUS_READY Source: <mab_serial_lib.lowlevel.LLProtocol object at 0x7f80b2738850>
[2021-11-09 11:43:35,941]INFO _observe_events() userlevel.py:506 Event label: EventLabel.ANSWER_RECV, Attachment: Answer node_id:200 cmd_code:MACHINE_STATUS, params:{'status_level': 9, 'cycle_step': 5, 'error_code': 201, 'cover_reserve': b'\x00', 'cover_availability': b'\x00', 'cover_enabled': b'\x00', 'container_reserve': b'\x00', 'container_availability': b'\x00', 'container_enabled': b'\x00', 'color_reserve': b'\x01\x00\x00\x00', 'container_presence': False, 'autocap_status': True, 'canlift_status': False, 'doors_status': True, 'clamp_position': 0, 'recirculation_status': b'\x00\x00\x00\x00', 'stirring_status': b'\x00\x00\x00\x00', 'slave_status': b'\x00\x00\x00\x00\x00\x00', 'can_on_plate': False, 'can_lifter_current_height': 0, 'can_lifter_range': 0, 'current_temperature': 65535, 'current_rel_humidity': 0, 'water_level': False, 'critical_temperature': False, 'temperature': 0, 'bases_carriage': False, 'circuit_engaged': 0, 'table_steps_position': 65535, 'autotest_cycles_number': 0, 'table_cleaning_status': b'\x00\x00\x00\x00', 'panel_table_status': False, 'photocells_status': 0, 'can_available': False, 'mixer_door_status': False, 'slave_enable_mask': b'\x01\x00\x00\x00\x00\x00', 'jar_photocells_status': 0, 'stop_formula': 0, 'punct_cleaning_proc': False, 'punct_recirc_proc': False, 'punctual_stirr_proc': False, 'refill_proc': False, 'dispensing_proc': False, 'cleaning_after_proc': False, 'temp_recirc_proc': False, 'reset_proc': False, 'temp_controll_proc': False, 'jar_pos_proc': False, 'eeprom_proc': False, 'pos_proc': False, 'self_rec_proc': False, 'crx_outputs_status': 0}, pending_cmd Source: <mab_serial_lib.lowlevel.LLProtocol object at 0x7f80b2738850>
[2021-11-09 11:43:35,942]INFO _update_recv_sts() userlevel.py:309 cmd id is MACHINE_STATUS
[2021-11-09 11:43:35,942]DEBUG _handle_answer() userlevel.py:339 Case 4
[2021-11-09 11:43:35,943]DEBUG _handle_answer() userlevel.py:350 Case 4-c
[2021-11-09 11:43:35,943]DEBUG _handle_answer() userlevel.py:352 Case 4-d
[2021-11-09 11:43:35,944]DEBUG _handle_answer() userlevel.py:361 Case 5
[2021-11-09 11:43:35,944]INFO set_node_status() userlevel.py:290 Setting node status to: NodeStatus.READY
[2021-11-09 11:43:35,944]INFO disconnect() driver.py:223 disconnecting
[2021-11-09 11:43:35,945]INFO _observe_driver() lowlevel.py:415 Event label: EventLabel.STATE_CHANGED, Attachment: State.DISCONNECTED Source: <mab_serial_lib.driver.SerialDriver object at 0x7f80b271bdc0>
[2021-11-09 11:43:35,946]INFO _observe_events() userlevel.py:506 Event label: EventLabel.STATE_CHANGED, Attachment: State.WAITING_FOR_DRIVER_CONNECTED Source: <mab_serial_lib.lowlevel.LLProtocol object at 0x7f80b2738850>
[2021-11-09 11:43:35,947]INFO read() driver.py:252 reading task cancelled
[2021-11-09 11:43:45,958]INFO disconnect() driver.py:223 disconnecting
[2021-11-09 11:43:45,959]INFO _observe_driver() lowlevel.py:415 Event label: EventLabel.STATE_CHANGED, Attachment: State.DISCONNECTED Source: <mab_serial_lib.driver.SerialDriver object at 0x7f80b271bdc0>
[2021-11-09 11:43:45,959]INFO _observe_events() userlevel.py:506 Event label: EventLabel.STATE_CHANGED, Attachment: State.WAITING_FOR_DRIVER_CONNECTED Source: <mab_serial_lib.lowlevel.LLProtocol object at 0x7f80b2738850>
[2021-11-09 11:43:45,980]DEBUG _send_usb_message() alfa_fw_upgrader.py:224 Writing data: 02 82 14 2A 5D 6F 9A 25 01 00
[2021-11-09 11:43:45,984]DEBUG _read_usb_message() alfa_fw_upgrader.py:242 Read data: 02 38 02 01 00 00 00 00 00 00 00 00 FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[2021-11-09 11:43:45,985]DEBUG _send_usb_message() alfa_fw_upgrader.py:224 Writing data: 02 82 14 2A 5D 6F 9A 25 01 01
[2021-11-09 11:43:46,004]DEBUG _read_usb_message() alfa_fw_upgrader.py:242 Read data: 02 38 02 01 00 17 00 00 00 41 00 00 FF 00 FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[2021-11-09 11:43:46,005]INFO __init__() alfa_fw_upgrader.py:537 Response to QUERY, address = 5888, length = 16640, proto_ver = 0, boot_ver = None
[2021-11-09 11:43:46,005]DEBUG _send_usb_message() alfa_fw_upgrader.py:224 Writing data: 04
[2021-11-09 11:43:46,006]DEBUG _send_usb_message() alfa_fw_upgrader.py:224 Writing data: 02 82 14 2A 5D 6F 9A 25 01 01
[2021-11-09 11:43:51,009]WARNING decorated() alfa_fw_upgrader.py:164 Tentative #1 failed - exception: [Errno 110] Operation timed out
[2021-11-09 11:43:51,010]DEBUG _send_usb_message() alfa_fw_upgrader.py:224 Writing data: 02 82 14 2A 5D 6F 9A 25 01 01
[2021-11-09 11:43:52,013]WARNING decorated() alfa_fw_upgrader.py:164 Tentative #2 failed - exception: [Errno 110] Operation timed out
[2021-11-09 11:43:52,013]DEBUG _send_usb_message() alfa_fw_upgrader.py:224 Writing data: 02 82 14 2A 5D 6F 9A 25 01 01
[2021-11-09 11:43:53,015]WARNING decorated() alfa_fw_upgrader.py:164 Tentative #3 failed - exception: [Errno 110] Operation timed out
[2021-11-09 11:43:53,016]DEBUG _send_usb_message() alfa_fw_upgrader.py:224 Writing data: 02 82 14 2A 5D 6F 9A 25 01 01
[2021-11-09 11:43:54,019]WARNING decorated() alfa_fw_upgrader.py:164 Tentative #4 failed - exception: [Errno 110] Operation timed out
[2021-11-09 11:43:54,020]DEBUG _send_usb_message() alfa_fw_upgrader.py:224 Writing data: 02 82 14 2A 5D 6F 9A 25 01 01
[2021-11-09 11:43:55,023]WARNING decorated() alfa_fw_upgrader.py:164 Tentative #5 failed - exception: [Errno 110] Operation timed out
[2021-11-09 11:43:55,024]WARNING decorated() alfa_fw_upgrader.py:166 Failed.
[2021-11-09 11:43:55,024]WARNING decorated() alfa_fw_upgrader.py:164 Tentative #1 failed - exception: [Errno 110] Operation timed out
[2021-11-09 11:43:55,025]DEBUG _send_usb_message() alfa_fw_upgrader.py:224 Writing data: 04
[2021-11-09 11:43:56,027]WARNING decorated() alfa_fw_upgrader.py:164 Tentative #2 failed - exception: [Errno 110] Operation timed out
[2021-11-09 11:43:56,028]DEBUG _send_usb_message() alfa_fw_upgrader.py:224 Writing data: 04
[2021-11-09 11:43:57,030]WARNING decorated() alfa_fw_upgrader.py:164 Tentative #3 failed - exception: [Errno 110] Operation timed out
[2021-11-09 11:43:57,031]DEBUG _send_usb_message() alfa_fw_upgrader.py:224 Writing data: 04
[2021-11-09 11:43:58,033]WARNING decorated() alfa_fw_upgrader.py:164 Tentative #4 failed - exception: [Errno 110] Operation timed out
[2021-11-09 11:43:58,034]DEBUG _send_usb_message() alfa_fw_upgrader.py:224 Writing data: 04
[2021-11-09 11:43:59,036]WARNING decorated() alfa_fw_upgrader.py:164 Tentative #5 failed - exception: [Errno 110] Operation timed out
[2021-11-09 11:43:59,037]WARNING decorated() alfa_fw_upgrader.py:166 Failed.
The following error occured during execution: Failed to erase ({})
Return value is 4
Traceback (most recent call last):
  File "/home/phil/work/sw/sw-programmazione-schede/src/alfa_fw_upgrader.py", line 672, in erase
    self.usb.ERASE()
  File "/home/phil/work/sw/sw-programmazione-schede/src/alfa_fw_upgrader.py", line 162, in decorated
    return method(self, *args, **kwargs)
  File "/home/phil/work/sw/sw-programmazione-schede/src/alfa_fw_upgrader.py", line 325, in ERASE
    self._send_usb_message(data)
  File "/home/phil/work/sw/sw-programmazione-schede/src/alfa_fw_upgrader.py", line 229, in _send_usb_message
    ret = self.dev.write(self.ep_out, data_to_send, timeout)
  File "/home/phil/work/sw/rs485-master-env/lib/python3.8/site-packages/usb/core.py", line 989, in write
    return fn(
  File "/home/phil/work/sw/rs485-master-env/lib/python3.8/site-packages/usb/backend/libusb1.py", line 855, in intr_write
    return self.__write(self.lib.libusb_interrupt_transfer,
  File "/home/phil/work/sw/rs485-master-env/lib/python3.8/site-packages/usb/backend/libusb1.py", line 938, in __write
    _check(retval)
  File "/home/phil/work/sw/rs485-master-env/lib/python3.8/site-packages/usb/backend/libusb1.py", line 602, in _check
    raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phil/work/sw/sw-programmazione-schede/src/alfa_fw_upgrader_app.py", line 403, in main
    ufl.erase()
  File "/home/phil/work/sw/sw-programmazione-schede/src/alfa_fw_upgrader.py", line 675, in erase
    raise RuntimeError("failed to perform erase")
RuntimeError: failed to perform erase
failed to update
```

**Comment by fgalfa** [comment]
Per ulteriori verifiche riporto link agli hex file usati: https://github.com/alfa-sw/sw-programmazione-schede/tree/8da97f6d907c330791bd62e2264b2e6f72997aac/tests/compatibility_tests/DESK

**Comment by micheleabelli** [comment]
Il problema non si presenta più dopo modifica al Boot MAB che, in caso di tentativo di aggiornamento FW su una Slave avente Boot Non compatibile o Non comunicante, determina un failure nella Verifica senza bloccarsi, rimanendo disponibile per altri aggiornamenti
