### ISSUE TITLE
Digest non salvato correttamente ed errata gestione dell'eccezione

### ISSUE THREAD

**Issue by fgalfa** [alfa-sw/sw-programmazione-schede#22]
Alla fine della programmazione di una scheda in modalità manuale il valore di digest non viene salvato correttamente: risulta 0 anziché quello impostato col comando precedente. In aggiunta l'eccezione provoca un'altra eccezione e l'interfaccia va in blocco.

```
 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00
[2021-12-15 09:09:54,945]DEBUG program() lib.py:740 programming on address 336736 chunk FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00
[2021-12-15 09:09:54,945]DEBUG _send_usb_message() lib.py:227 Writing data: 05 B0 A7 02 00 38 00 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00
[2021-12-15 09:09:54,947]DEBUG program() lib.py:740 programming on address 336792 chunk FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00
[2021-12-15 09:09:54,954]DEBUG _send_usb_message() lib.py:227 Writing data: 05 CC A7 02 00 38 00 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00
[2021-12-15 09:09:54,956]DEBUG program() lib.py:738 Chunk len is 48
[2021-12-15 09:09:54,956]DEBUG program() lib.py:740 programming on address 336848 chunk FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00
[2021-12-15 09:09:54,956]DEBUG _send_usb_message() lib.py:227 Writing data: 05 E8 A7 02 00 30 00 00 00 00 00 00 00 00 00 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00
[2021-12-15 09:09:54,958]DEBUG _send_usb_message() lib.py:227 Writing data: 06 AB EE FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
[2021-12-15 09:09:54,959]DEBUG _send_usb_message() lib.py:227 Writing data: 02 82 14 2A 5D 6F 9A 25 01 FF
[2021-12-15 09:09:54,962]DEBUG _read_usb_message() lib.py:249 Read data: 02 38 02 01 00 2C 00 00 00 7C 02 00 FF 01 01 09 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[2021-12-15 09:09:54,962]INFO _update_from_query() lib.py:548 Response to QUERY, address = 11264, length = 162816, proto_ver = 1, boot_ver = (1, 9, 3) boot_status = 0 digest = 0
Traceback (most recent call last):
  File "alfa_fw_upgrader\lib.py", line 758, in program
    raise RuntimeError(
RuntimeError: digest not correctly saved by bootloader

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "alfa_fw_upgrader\app.py", line 159, in process_manual
    self.ufl.program(self.program_data)
  File "alfa_fw_upgrader\lib.py", line 762, in program
    raise RuntimeError("program failed during finalization")
RuntimeError: program failed during finalization

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eel\__init__.py", line 281, in _process_message
  File "alfa_fw_upgrader\app.py", line 269, in process_manual
    self.process_manual(setup_dict)
  File "alfa_fw_upgrader\app.py", line 164, in process_manual
    "output": self._get_output("PROGRAM_FAILED")})
  File "alfa_fw_upgrader\app.py", line 52, in _get_output
    error_item = Application.errors_dict[error_key]
KeyError: 'PROGRAM_FAILED'

```

**Comment by fgalfa** [comment]
Il programma caricato era per un'altra scheda quindi la situazione era anomala, tuttavia in teoria il problema non si sarebbe dovuto presentare.

**Comment by fgalfa** [comment]
@micheleabelli questa problematica è stata corretta? nel caso possiamo chiudere

**Comment by micheleabelli** [comment]
Problema sistemato.
